site_name: 文档中心
repo_url: https://github.com/trustoceanltd/docs
repo_name: TRUSTOCEAN/DOCS
plugins:
  - search
theme:
  language: zh
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Encryption365:
      - 介绍: encryption365/introduction.md
      - 调用逻辑: encryption365/logic.md
      - 请求响应: encryption365/request.md
      - 错误请求: encryption365/error.md
      - 接口认证: encryption365/authentication.md
      - API 接口:
        - 注册设备: encryption365/api/client/create.md
        - 产品列表: encryption365/api/account/products.md
        - 创建证书: encryption365/api/order/create.md
        - 查询证书: encryption365/api/cert/details.md
        - 修改验证: encryption365/api/cert/change_dcv.md
        - 吊销证书: encryption365/api/cert/revoke.md
        - 重启验证: encryption365/api/cert/challenge.md