site_name: 文档中心
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Encryption365:
      - 介绍: encryption365/introduction.md
      - 调用逻辑: encryption365/logic.md
      - 请求响应: encryption365/request.md
      - 错误请求: encryption365/error.md
      - 接口认证: encryption365/authentication.md
      - 注册设备: encryption365/client/create.md
      - 产品列表: encryption365/account/products.md
      - 创建证书: encryption365/order/create.md
      - 查询证书: encryption365/cert/details.md
      - 修改验证: encryption365/cert/change_dcv.md
      - 吊销证书: encryption365/cert/revoke.md
      - 重启验证: encryption365/cert/challenge.md